In [17]:
import numpy as np
 
X = np.array(([0.35, 0.7], [0.8, 0.7], [0.6, 0.9]), dtype=float)
y = np.array(([0.9], [0.2], [0.8]), dtype=float)
 
X = X/np.amax(X, axis=0) # maximum of X array
y = y/100 # max test score is 100
 
class Neural_Network(object):
  def __init__(self):
    #parameters
    self.inputSize = 2
    self.outputSize = 1
    self.hiddenSize = 3
    self.hiddenSize = 4
 
    #weights
    self.W1 = np.random.randn(self.inputSize, self.hiddenSize) 
    self.W2 = np.random.randn(self.hiddenSize, self.outputSize) 
 
  def forward(self, X):
    #forward propagation through our network
    self.z = np.dot(X, self.W1) # dot product of X (input) and first set of weights
    self.z2 = self.sigmoid(self.z) # activation function
    self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
    o = self.sigmoid(self.z3) # final activation function
    return o 
 
  def sigmoid(self, s):
    # activation function 
    return 1/(1+np.exp(-s))

  def sigmoidPrime(self, s):
    #derivative of sigmoid
    return s * (1 - s)

  def backward(self, X, y, o):
    # backward propgate through the network
    self.o_error = y - o # error in output
    self.o_delta = self.o_error*self.sigmoidPrime(o) # applying derivative of sigmoid to error

    self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
    self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

    self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
    self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights

  def train (self, X, y):
    o = self.forward(X)
    self.backward(X, y, o)
 
NN = Neural_Network()
for i in range(1000): # trains the NN 1,000 times
  print ("Input: \n" + str(X)) 
  print ("Actual Output: \n" + str(y)) 
  print ("Predicted Output: \n" + str(NN.forward(X))) 
  print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss
  print ("\n")
  NN.train(X, y)

Показано результат, скорочений до останніх рядків (5000).
Predicted Output: 
[[0.01620928]
 [0.01408193]
 [0.01234902]]
Loss: 
7.228693478029032e-05


Input: 
[[0.4375     0.77777778]
 [1.         0.77777778]
 [0.75       1.        ]]
Actual Output: 
[[0.009]
 [0.002]
 [0.008]]
Predicted Output: 
[[0.01619932]
 [0.01407317]
 [0.01234097]]
Loss: 
7.214522144507088e-05


Input: 
[[0.4375     0.77777778]
 [1.         0.77777778]
 [0.75       1.        ]]
Actual Output: 
[[0.009]
 [0.002]
 [0.008]]
Predicted Output: 
[[0.01618939]
 [0.01406443]
 [0.01233293]]
Loss: 
7.200399270099971e-05


Input: 
[[0.4375     0.77777778]
 [1.         0.77777778]
 [0.75       1.        ]]
Actual Output: 
[[0.009]
 [0.002]
 [0.008]]
Predicted Output: 
[[0.01617947]
 [0.0140557 ]
 [0.01232492]]
Loss: 
7.1863246248167e-05


Input: 
[[0.4375     0.77777778]
 [1.         0.77777778]
 [0.75       1.        ]]
Actual Output: 
[[0.009]
 [0.002]
 [0.008]]
Predicted Output: 
[[0.01616958]
 [0.014047  ]
 [0.01231692]